apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-controller
    spec:
      serviceAccountName: ko-builder
      containers:
      - name: echo-controller
        image: github.com/feloy/kopond/cmd/echo
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"