apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo-controller
spec:
  selector:
    app: echo-controller
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer